-- require("base")
-- require("autocmds")
-- require("options")
-- require("keymaps")
-- require("colorscheme")
-- require("plugins")

require("dhara.plugins-setup")
require("dhara.core.options")
require("dhara.core.keymaps")
require("dhara.core.colorscheme")
require("dhara.plugins.comment")
require("dhara.plugins.nvim-tree")
require("dhara.plugins.lualine")
require("dhara.plugins.telescope")
require("dhara.plugins.nvim-cmp")
require("dhara.plugins.lsp.mason")
require("dhara.plugins.lsp.lspsaga")
require("dhara.plugins.lsp.lspconfig")
require("dhara.plugins.lsp.null-ls")
require("dhara.plugins.autopairs")
require("dhara.plugins.treesitter")
require("dhara.plugins.gitsigns")
